name: Kakarot-Dimensions
version: 1.0
main: com.kakarot.Main
author: SpaceyDCO

description: A custom dimension system for players to own Hyperbolic Chambers.

commands:
  chamber:
    description: Main command for the plugin.
    usage: /<command> [subcommand]
    aliases: [chambers]
  fragments:
    description: Admin command to manage player dimensional fragments
    usage: /<command> <give|set|take> <player> <amount>
    aliases: [dimfragments, kakarotfragments]
    # permission: kakarot.admin.fragments ADD LATER

depend: [WorldEdit, Kakarot]
loadbefore: [WorldEdit, Kakarot]